spring:
  application:
    name: Employee management system
  datasource:
    url: jdbc:mysql://localhost:3306/ems?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: false
  data:
    jpa:
      repositories:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: codehustle98@gmail.com
    password: hymhgijczkpsfxxs
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
server:
  servlet:
    context-path: /ems/api
  port: 8080
ems:
  cron:
    email-scheduler: 1 * * * * ?
