spring:
  application:
    name: Employee management system
  datasource:
    url: jdbc:mysql://localhost:3306/ems?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySql5Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
  data:
    jpa:
      repositories:
        enabled: true
  liquibase:
    change-log: classpath:db/master.xml
server:
  servlet:
    context-path: /ems/api/